name: Push to dev and test

on:
  push:
    branches:
    - dev

env:
  GCS_BUCKET: ${{ secrets.TEST_BUCKET }}

permissions:
  contents: 'read'
  id-token: write # This is required for requesting the JWT

jobs:
  qa_deploy_and_test:
    runs-on: ubuntu-latest
    steps:
      - id: 'checkout'
        name: Checkout Repo
        uses: actions/checkout@v2

      - id: auth
        name: Authorise with GCP Project
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/757581767293/locations/global/workloadIdentityPools/test-wif-pool/providers/test-wif-provider'
          service_account: 'github-actions-qa@crc-test-site.iam.gserviceaccount.com'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0

      - id: 'sync_content'
        name: Sync Content to Test Bucket
        run: gsutil -m rsync -R ${{ github.workspace }}/content gs://$GCS_BUCKET

      - name: Run Page Content Tests
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          spec: ${{ github.workspace }}/cypress/e2e/qa_page_content.cy.js
          browser: chrome