name: Push to dev and test

on:
  push:
    branches:
    - dev

env:
  GCS_BUCKET: ${{ secrets.TEST_BUCKET }}

permissions:
  contents: 'read'
  id-token: write # This is required for requesting the JWT

jobs:
  qa-deploy_and_test:
    runs-on: ubuntu-latest
    #container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - id: 'checkout'
        name: Checkout Repo
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'https://iam.googleapis.com/projects/757581767293/locations/global/workloadIdentityPools/test-wif-pool/providers/test-wif-provider'
          service_account: 'github-actions-qa@crc-test-site.iam.gserviceaccount.com'

      - uses: google-github-actions/setup-gcloud@v0

      - id: 'sync_content'
        name: Sync Content to Test Bucket
        run: gcloud storage ls
        #run: gcloud config set project ${{ secrets.PROD_PROJECT }}
        
      #- run: gsutil -m rsync -R ${{ github.workspace }}/content gs://$GCS_BUCKET
      #- run: gcloud storage ls

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      #- name: Cypress run --spec ${{ github.workspace }}/cypress/e2e/qa_page_content.cy.js
      #  uses: cypress-io/github-action@v4 # use the explicit version number
      #  with:
          # Specify Browser since container image is compile with Firefox
      #    browser: chrome